# Generated by Django 4.2.3 on 2023-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
