# Generated by Django 4.2.3 on 2023-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_floor_floor_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
