# Generated by Django 4.2.3 on 2023-07-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_alter_elevator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='id',
            new_name='elevator_id',
        ),
    ]
