# Generated by Django 4.2.3 on 2023-07-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_remove_request_destination_elevator_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='last_stop',
            new_name='current_stop',
        ),
    ]
